[profile.default]
src = "src"
out = "out"
libs = ["lib"]
tab_width = 2
evm_version = "cancun"
via_ir = true
solc_version = "0.8.28"
remappings = [
    "src/=src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
